### ISSUE TITLE
how to add user in channel 

### ISSUE THREAD

**Issue by sagar3506** [gsusI/Telegram-Group-or-Channel-users-to-CSV#1]
hey i like ur script but i dont known how to add users in channel after scraping

i try with option 2 but its show error

![image](https://user-images.githubusercontent.com/9415704/72927473-4e78cc80-3d7c-11ea-9224-bdbb59d99546.png)

**Comment by mantoayo** [comment]
i have the same errors when i try add members from .csv to group or channel

**Comment by saretto28** [comment]
> ho gli stessi errori quando provo ad aggiungere membri da .csv al gruppo o al canale

same problem you too could solve?

**Comment by mantoayo** [comment]
Unfortunately not... :/

**Comment by gsusI** [comment]
To run option 2, you'll need to pass the CSV path as a parameter, when running the script. In your case, looks like it'd be:
`python3 sp.py list_of_users.csv`

Let me know if that solves the problem

**Comment by mantoayo** [comment]
I run the script through PyCharm. Can you explain to me step by step where in the script and what information should I put for option 2 to work? I have scrapped list.csv

**Comment by mantoayo** [comment]
> To run option 2, you'll need to pass the CSV path as a parameter, when running the script. In your case, looks like it'd be:
> `python3 sp.py list_of_users.csv`
> 
> Let me know if that solves the problem

Ok i run this script through linux and work well but only for group, i cant add any members to channel....

**Comment by gsusI** [comment]
As specified in the README file: _Adding users by Username expects a CSV file with one username per line. Adding users by User ID expects a CSV file such as: username,user_id,user_access_hash_

Is the format of your CSV correct?

**Comment by iravkr** [comment]
Hi...Sorry to disturb you. Can you please share how to add my contact list to my channel. Thanks in advance.

**Comment by itismrx** [comment]
Hay... I was hoping if you could tell me how can I add users to my channel.
thanks

**Comment by gsusI** [comment]
I believe the issue is solved, if to add users to a channel please prepare the CSV with the appropriate format and use the following command: `python3 telethon-bot-add-users-to-groups.py list_of_users.csv`

**Comment by itismrx** [comment]
I can't find sp.py .

**Comment by iravkr** [comment]
He renamed it...this is the same file as on github..though the channel part id not working..I hope he helps us with the channel also...

**Comment by gsusI** [comment]
I'm not actively using this anymore, please feel free to contribute to the codebase and send a pull request.
