### ISSUE TITLE
Problems by Showing CSV

### ISSUE THREAD

**Issue by dumspirmamustuebimur** [gsusI/Telegram-Group-or-Channel-users-to-CSV#2]
Hello dear, 
when i took option 3 after scraping members from a channel i cant show my csv. Here you can see the screenshot. 
i would be very pleased about help

best regards
![2020-03-25 14_25_34-VM-tgra  wird ausgeführt  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/62650495/77541492-0756a700-6ea5-11ea-8788-aa30acd8bb27.png)

**Comment by gsusI** [comment]
To show a CSV you need to pass it as a parameter. It will be in the same folder where you ran the script before.

Please confirm if that solved your issue.

**Comment by gsusI** [comment]
Haven't heard back in a while, closing this issue now.
