### ISSUE TITLE
how to Add users from CSV to Group (CSV must be passed as a parameter to the script

### ISSUE THREAD

**Issue by abhisak74** [gsusI/Telegram-Group-or-Channel-users-to-CSV#3]
bro please help me how to Add users from CSV to Group (CSV must be passed as a parameter to the script on pycham

**Comment by abhisak74** [comment]
![Cpythonapture](https://user-images.githubusercontent.com/69030358/89007376-4058c980-d326-11ea-9e91-ec17c9153896.PNG)
please help bro

**Comment by abhisak74** [comment]
i got it

**Comment by gsusI** [comment]
If you feel the documentation could be more helpful, please modify it and submit a pull request, happy to have collaborators making this project better 😄

**Comment by tuminzee** [comment]
You have to pass the csv file as an argument
`python telethon-bot-add-users-to-groups.py members.csv `
